### ISSUE TITLE
Netplan configuration missing on reboot

### ISSUE THREAD

**Issue by mabasic** [mrlesmithjr/ansible-netplan#22]
For some reason after I run this role , the configuration file is applied correctly, but not saved to etc/netplan.

Also my default 00-installer-config.yaml file is deleted. So, when I reboot the machine I have no connectivity.

Any clues?

What is the default behavior of this role?

**Comment by mabasic** [comment]
Figured it out after reading the source code. The documentation of options could be better...

**Comment by mrlesmithjr** [comment]
@mabasic Glad you figured it out. Please feel free to provide any information to make the documentation better. PR's are always an option.
