### ISSUE TITLE
Maintained-by-ansible comment

### ISSUE THREAD

**Issue by yaiqsa** [mrlesmithjr/ansible-netplan#27]
**Is your feature request related to a problem? Please describe.**
I'd like the possibility to ad a 'do not change this file' warning at the top of the generated netplan files.

**Describe the solution you'd like**
I would suggest just putting this snippet at the top of the template:
```jinja
{% if netplan_managed_comment is not none %}
# {{ netplan_managed_comment }}
{% endif %}
```

By default this variable could either be empty, a reference to `ansible_managed`, or a custom string.
I implemented this idea in [my personal fork](https://github.com/Burathar/ansible-netplan) already.

**Describe alternatives you've considered**
I could run a separate task after this role to add the comment, but that would lead to more cutter and filechanges.

**Additional context**
I think this feature is quite self-explanatory 😅

**Comment by mrlesmithjr** [comment]
@Burathar I like this idea and PR's are more than welcomed!

**Comment by yaiqsa** [comment]
> @Burathar I like this idea and PR's are more than welcomed!

I will try to find the time to implement something, but I've got quite a backlog of projects 😅
