### ISSUE TITLE
Support tunnels configuration with netplan

### ISSUE THREAD

**Issue by ghost** [mrlesmithjr/ansible-netplan#34]
I want to configure ipip tunnel interface with this role but I can't.

This commit would help me with the solution:
https://github.com/mrlesmithjr/ansible-netplan/compare/master...kichay:ansible-netplan:tunnels

https://github.com/mrlesmithjr/.github/blob/main/CONTRIBUTING.md - here you ask for the discussion. Is my solution satisfactory?

**Comment by mrlesmithjr** [comment]
@kichay - I think this would be something good to add but would like to include some examples in the `README.md` or `defaults/main.yml`.
