### ISSUE TITLE
Option to not create backup of /etc/netplan yml file

### ISSUE THREAD

**Issue by Apollo3zehn** [mrlesmithjr/ansible-netplan#42]
**Is your feature request related to a problem? Please describe.**
I am running the Ansible playbook with this role daily using Semaphore (an Ansible GUI). Problem is that after 365 days I get 365 backup files which I do not want or need.

**Describe the solution you'd like**
I would be great if the backup option could be disabled: https://github.com/mrlesmithjr/ansible-netplan/blob/04f5dbd2ffe017227097b010dd31e2bae1587ae1/tasks/configure.yml#L7

**Describe alternatives you've considered**
-

**Additional context**
-

Thank you very much!

**Comment by mrlesmithjr** [comment]
@Apollo3zehn PR's are welcomed if you'd like to take this on.
