### ISSUE TITLE
Netplan role removes configurations by default

### ISSUE THREAD

**Issue by egorperesada** [mrlesmithjr/ansible-netplan#50]
**Describe the bug**
If we are using default variables, this role remove all existing netplan configuration on server and add empty ansible-config.yaml configuration

**To Reproduce**
1. do not reassign any netplan variables
2. run playbook with this role
3. $ ls /etc/netplan # on your server
4. will see /etc/netplan/ansible-config.yaml
5. $ cat /etc/netplan/ansible-config.yaml
6. will see it's empty

**Expected behavior**
Existing netplan configuration exists in /etc/netplan

**Screenshots**
![telegram-cloud-photo-size-2-5280494078494103384-x](https://github.com/mrlesmithjr/ansible-netplan/assets/36980920/ee454fad-e2ce-48a4-bfb6-627e37285b4f)
![telegram-cloud-photo-size-2-5280494078494103386-m](https://github.com/mrlesmithjr/ansible-netplan/assets/36980920/01684222-ecb2-4b67-8a20-867cbecbbca8)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Additional context**
This happens because your default `netplan_configuration` asssigned as `{}` (object), but in task conditions it's expected to be not an array `[]`

**Comment by richard-scott** [comment]
I'd assumed that setting netplan_remove_existing to False would mean any new config would merge with the existing config. I was wrong! ;-(
