### ISSUE TITLE
Latest github changes are not published on Ansible Galaxy

### ISSUE THREAD

**Issue by webash** [mrlesmithjr/ansible-netplan#52]
**Describe the bug**
v0.4.1 is the latest version of the role on Ansible Galaxy, but there have been (minor) commits since then including #48 / #49 

**To Reproduce**
1. $ ansible-galaxy role install mrlesmithjr.netplan
2. $ ansible-galaxy role list
   ```
   - mrlesmithjr.netplan, v0.4.1
   ```

**Expected behavior**
Version should be higher than v0.4.1 because that was [released before](https://github.com/mrlesmithjr/ansible-netplan/releases) the latest modifications (#49).

**Comment by cradle8810** [comment]
This bug or forgetting to push into ansible-galaxy makes failed to install Netplan into Ubuntu 24.04. I got around this using the direct reference method to the git repository commits. Could you fix this please?

**Comment by mrlesmithjr** [comment]
This has been updated on Ansible Galaxy
