### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by nkakouros** [mrlesmithjr/ansible-netplan#8]
The update of the template file in a recent commit broke my playbooks. It would be nice to have versions to avoid suck breakages during updates.

**Comment by mrlesmithjr** [comment]
@tterranigma Can you share what exactly broke to see if the logic can be added to ensure that this doesn't happen to others? Also, versioning is in the plans going forward as well.

**Comment by nkakouros** [comment]
There were two issues. One was that I didn't have a `network` key for the `netplan_configuration` variable (but still the role installed without issues). The other was that I didn't have a `version: 2` key. Perhaps the template could be improved to allow for missing keys?

**Comment by mrlesmithjr** [comment]
Thanks for this @tterranigma

**Comment by mrlesmithjr** [comment]
First version has been released `v0.1.0`

**Comment by Clement-TS** [comment]
Would it be possible to have a small example in the README documentation? 
Thank you!

**Comment by mrlesmithjr** [comment]
@Clement-TS I assume you are just looking for a generated config?

**Comment by nkakouros** [comment]
@mrlesmithjr thanks for having taken care of this. I think this can be closed.
