### ISSUE TITLE
Question about changing ip addresses

### ISSUE THREAD

**Issue by generalconsensus** [mrlesmithjr/ansible-netplan#9]
If I change ip addresses the ip address i'm currently accessing the machine on changes, is there a theory on what we can do to handle this. Perhaps a wait flag etc

**Comment by mrlesmithjr** [comment]
You would need to definitely orchestrate that. Your inventory will be out of sync for sure if you are using static IP addresses and not using DNS resolution.

**Comment by generalconsensus** [comment]
Can you give an example of using dns resolution and automatic dns management via ansible. i'm taking it that this is the next level, have you read up on this somewhere?

**Comment by mrlesmithjr** [comment]
In your inventory, ensure that all of your hosts are added as DNS/FQDN names. Do **NOT**, add IP into inventory as `ansible_host`.
```bash
[db_servers]
db01.example.org
db02.example.org

[web_servers]
web01.example.org
web02.example.org
```

If you want to change the static IP address on a host:
- Change IP on host
- Ensure DNS is updated to reflect change
- Proceed

Now, the catch here is, ensuring that you can orchestrate the DNS server. My preference for DNS, is PowerDNS.

In regard to reading up on this, no, but have done this at massive scale across datacenters. Possibly a blog post is in order?

Hope this helps!

**Comment by generalconsensus** [comment]
Great assist, thanks!
